FROM python:3.9

COPY requirements.txt .
RUN pip install --no-cache-dir -rrequirements.txt

WORKDIR /var/src/

COPY . .
RUN pip install .

RUN mkdir /var/data
ENV TSKTSK_DB_PATH /var/data/tsktsk.sqlite

CMD tsktsk-bot
